src/Entity/Prescription.php
<?php

namespace App\Entity;

use App\Repository\PrescriptionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PrescriptionRepository::class)
 */
class Prescription
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $qrcode;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_archived = false;

    /**
     * @ORM\OneToMany(targetEntity=PresMedic::class, mappedBy="prescription")
     */
    private $presMedics;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="prescriptions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="text")
     */
    private $medications;

    /**
     * @ORM\Column(type="string", length=80)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=80)
     */
    private $lastname;

    /**
     * @ORM\Column(type="integer")
     */
    private $security_Social_Number;

    public function __construct()
    {
        $this->created_at = new \DateTime('now');
        $this->presMedics = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getQrcode(): ?string
    {
        return $this->qrcode;
    }

    public function setQrcode(?string $qrcode): self
    {
        $this->qrcode = $qrcode;

        return $this;
    }

    public function getIsArchived(): ?bool
    {
        return $this->is_archived;
    }

    public function setIsArchived(bool $is_archived): self
    {
        $this->is_archived = $is_archived;

        return $this;
    }

    /**
     * @return Collection|PresMedic[]
     */
    public function getPresMedics(): Collection
    {
        return $this->presMedics;
    }

    public function addPresMedic(PresMedic $presMedic): self
    {
        if (!$this->presMedics->contains($presMedic)) {
            $this->presMedics[] = $presMedic;
            $presMedic->setPrescription($this);
        }

        return $this;
    }

    public function removePresMedic(PresMedic $presMedic): self
    {
        if ($this->presMedics->contains($presMedic)) {
            $this->presMedics->removeElement($presMedic);
            // set the owning side to null (unless already changed)
            if ($presMedic->getPrescription() === $this) {
                $presMedic->setPrescription(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getMedications(): ?string
    {
        return $this->medications;
    }

    public function setMedications(string $medications): self
    {
        $this->medications = $medications;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getSecuritySocialNumber(): ?int
    {
        return $this->security_Social_Number;
    }

    public function setSecuritySocialNumber(int $security_Social_Number): self
    {
        $this->security_Social_Number = $security_Social_Number;

        return $this;
    }
}

src/Form/PrescriptionType.php
<?php

namespace App\Form;

use App\Entity\Prescription;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PrescriptionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('medications')
            ->add('firstname')
            ->add('lastname')
            ->add('security_social_number')
            //->add('qrcode')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Prescription::class,
        ]);
    }
}

src/Controller/PrescriptionController.php
<?php

namespace App\Controller;

use App\Entity\Prescription;
use App\Form\PrescriptionType;
use App\Repository\PrescriptionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/prescription")
 */
class PrescriptionController extends AbstractController
{
    /**
     * @Route("/", name="prescription_index", methods={"GET"})
     */
    public function index(PrescriptionRepository $prescriptionRepository): Response
    {
        return $this->render('prescription/index.html.twig', [
            'prescriptions' => $prescriptionRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="prescription_new", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $prescription = new Prescription();
        $form = $this->createForm(PrescriptionType::class, $prescription);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($prescription);
            $entityManager->flush();
            $this->addFlash('success', 'The prescription is sent ! ');

            return $this->redirectToRoute('prescription_new');
        }

        return $this->render('prescription/new.html.twig', [
            'prescription' => $prescription,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="prescription_show", methods={"GET"})
     */
    public function show(Prescription $prescription): Response
    {
        return $this->render('prescription/show.html.twig', [
            'prescription' => $prescription,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="prescription_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Prescription $prescription): Response
    {
        $form = $this->createForm(PrescriptionType::class, $prescription);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('prescription_index');
        }

        return $this->render('prescription/edit.html.twig', [
            'prescription' => $prescription,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="prescription_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Prescription $prescription): Response
    {
        if ($this->isCsrfTokenValid('delete'.$prescription->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($prescription);
            $entityManager->flush();
        }

        return $this->redirectToRoute('prescription_index');
    }
}

templates/prescription/_delete_form.html.twig
<form method="post" action="{{ path('prescription_delete', {'id': prescription.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ prescription.id) }}">
    <button class="btn">Delete</button>
</form>

templates/prescription/_form.html.twig
{{ form_start(form) }}
    {{ form_row(form.name, { 'label': 'Doctor Name'})}}
    <div class="row">
        <div class="col">{{ form_row(form.firstname)}}</div>
        <div class="col">{{ form_row(form.lastname)}}</div>
    </div>
    {{ form_row(form.security_social_number)}}
    {{ form_rest(form)}}
    <button class="btn btn-info mt-2">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/prescription/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Prescription{% endblock %}

{% block body %}
    <h1>Edit Prescription</h1>

    {{ include('prescription/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('prescription_index') }}">back to list</a>

    {{ include('prescription/_delete_form.html.twig') }}
{% endblock %}

templates/prescription/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Prescriptions{% endblock %}

{% block body %}
<div class="container col-sm-12 col-md-6 col-lg-6">
    <h1 class="text-center mt-5">{{ app.user.firstname }} {{ app.user.lastname }}</h1>
    <div class="d-flex mt-5">
        <h3>Prescriptions</h3>
        <a class="btn btn-warning ml-3" href="{{ path('booking_calendar',{'id' : '1'}) }}">Calendar</a>
    </div>
    {% for prescription in prescriptions %}
    <ul class="list-group my-3">
        <li class="list-group-item"><strong>Doctor: </strong>{{ prescription.name }}</li>
        <li class="list-group-item"><strong>Date: </strong>{{ prescription.createdAt ? prescription.createdAt|date('Y-m-d') : '' }}</li>
        {% if prescription.isArchived == false %}
        <li class="list-group-item"><i class=" btn btn-success far fa-circle"></i></li>
        {% elseif prescription.isArchived == true %}
        <li class="list-group-item"><i class="btn btn-danger fas fa-times"></i></li>
        {% endif %}
    </ul>
    <a class="btn btn-info mb-5" href="{{ path('prescription_show', {'id': prescription.id}) }}">SHOW</a>
    {% endfor %}
</div>
{% endblock %}

templates/prescription/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Prescription{% endblock %}

{% block body %}
    <div class="container mt-5 col-lg-5 col-md-5">
        <h1 class="text-center mb-5">Create new Prescription</h1>
        {{ include('prescription/_form.html.twig') }}
    </div>
{% endblock %}

templates/prescription/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Prescription{% endblock %}

{% block body %}
    <div class="container col-sm-12 col-md-6 col-lg-6">
        <h1 class="text-center my-5">Prescription</h1>
        {% if prescription.isArchived == false %}
        <a class="btn btn-dark my-3" href="{{ path('prescription_index') }}">Back</a>
        {% endif %}
        <div class="d-md-flex d-lg-flex">
            <ul class="list-group list-group-flush mt-4 mr-5">
                <li class="list-group-item"><strong>Date: </strong> {{ prescription.createdAt ? prescription.createdAt|date('Y-m-d') : '' }}</li>
                <li class="list-group-item"><strong>Patient: </strong> {{ prescription.firstname }} {{ prescription.lastname }}</li>
                <li class="list-group-item"><strong>Medications: </strong><br>{{ prescription.medications | nl2br}}</li>
                <li class="list-group-item"><strong>Doctor: </strong> {{ prescription.name }}</li>
            </ul>
            <div class="ml-5">
                <img src="https://www.tutsmake.com/wp-content/uploads/2019/02/simple-qr-code-image.png" alt="">
            </div>
        </div>
        <div class="d-flex my-5">
            {% if prescription.isArchived == false %}
            <a class="btn btn-success mr-4" href="{{ path('pharma') }}">Pharmacy</a>
            <a class="btn btn-success" href="{{ path('drone') }}">Drone</a>
            {% elseif prescription.isArchived == true %}
            <a class="btn btn-dark my-3" href="{{ path('prescription_index') }}">Back</a>
            {% endif %}
        </div>
    </div>
{% endblock %}